name: ttyd server
description: Run ttyd server
author: zongou

branding:
  icon: "code"
  color: "yellow"

inputs:
  credential:
    description: "Credential for basic authentication (format: username:password)"
    required: true
  command:
    description: "Command to run"
    required: false
  port:
    description: "Port for ttyd server"
    required: false
    default: 7681
  enableZmodem:
    description: "Enable Zmodem support"
    required: false
    default: true
  enableTrzsz:
    description: "Enable Trzsz support"
    required: false
    default: true
  enableSixel:
    description: "Enable Sixel support"
    required: false
    default: true

runs:
  using: composite

  steps:
    - name: Setup install dir
      shell: bash
      run: |
        INSTALL_DIR="${{ runner.temp }}/install_dir"
        INSTALL_DIR_FORMATTED=${INSTALL_DIR}
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          INSTALL_DIR_FORMATTED=$(cygpath -w ${INSTALL_DIR})
        fi

        mkdir -p ${INSTALL_DIR}
        echo "Using install dir ${INSTALL_DIR}"
        echo ${INSTALL_DIR_FORMATTED} >> $GITHUB_PATH
        echo INSTALL_DIR=${INSTALL_DIR_FORMATTED} >> $GITHUB_ENV

    - name: Get cloudflared
      working-directory: ${{ env.INSTALL_DIR }}
      shell: bash
      run: |
        if ! command -v cloudflared >/dev/null 2>&1; then
          CLOUDFLARED_VERSION=$(curl -s -S -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/cloudflare/cloudflared/releases | jq -r .[0].tag_name)

          case $(uname -m) in
          aarch64 | arm64) CLOUDFLARED_ARCH=arm64 ;;
          x86_64) CLOUDFLARED_ARCH=amd64;;
          *) echo "Unsupported architecture" && exit 1 ;;
          esac

          case ${{ runner.os }} in
          Linux) curl -LkSs https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-linux-${CLOUDFLARED_ARCH} > cloudflared  && chmod +x cloudflared;;
          Windows) curl -LkSs https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-windows-${CLOUDFLARED_ARCH}.exe > cloudflared.exe ;;
          macOS) curl -LkSs https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-darwin-${CLOUDFLARED_ARCH}.tgz | gzip -d | tar -x ;;
          esac
        fi
        cloudflared --version

    - name: Get ttyd
      working-directory: ${{ env.INSTALL_DIR }}
      shell: bash
      run: |
        if ! command -v ttyd >/dev/null 2>&1; then
          TTYD_VERSION=$(curl -s -S -H "Authorization: Bearer ${{ github.token }}" https://api.github.com/repos/zongou/ttyd/releases | jq -r .[0].tag_name)

          case ${{ runner.os }} in
          Linux) 
            case $(uname -m) in
            aarch64 | arm64) TTYD_ARCH=aarch64 ;;
            x86_64) TTYD_ARCH=x86_64;;
            *) echo "Unsupported architecture" && exit 1 ;;
            esac
            curl -LkSs https://github.com/zongou/ttyd/releases/download/${TTYD_VERSION}/ttyd.${TTYD_ARCH} > ttyd  && chmod +x ttyd
            ;;
          Windows) 
            case $(uname -m) in
            aarch64 | arm64) TTYD_ARCH=aarch64 ;;
            x86_64) TTYD_ARCH=msvc;;
            x86) TTYD_ARCH=win32;;
            *) echo "Unsupported architecture" && exit 1 ;;
            esac
            curl -LkSs https://github.com/zongou/ttyd/releases/download/${TTYD_VERSION}/ttyd.${TTYD_ARCH}.exe > ttyd.exe
            ;;
          # macOS)  curl -LkSs https://github.com/zongou/ttyd/releases/download/${TTYD_VERSION}/ttyd.${TTYD_ARCH} > ttyd  && chmod +x ttyd;;
          esac
        fi
        ttyd --version

    - name: Run ttyd server
      env: 
        TTYD_LOG: ${{ runner.temp }}/ttyd.log
        CLOUDFLARED_LOG: ${{ runner.temp }}/cloudflared.log
        PORT: ${{ inputs.port }}
      shell: bash
      run: |
        nohup ttyd \
          --credential ${{inputs.credential}} \
          --port ${PORT} \
          --client-option enableZmodem=${{ inputs.enableZmodem }} \
          --client-option enableTrzsz=${{ inputs.enableTrzsz }} \
          --client-option enableSixel=${{ inputs.enableSixel }} \
          ${{ inputs.command || runner.os == 'Windows' && 'powershell' || 'bash -l' }} > "${TTYD_LOG}" 2>&1 &

        nohup cloudflared tunnel --url localhost:${PORT} > "${CLOUDFLARED_LOG}" 2>&1 &

        while true; do
            if cat "${CLOUDFLARED_LOG}" | grep -Eo "https://.+\.trycloudflare\.com"; then
                break
            fi
            sleep 1
        done
