name: Test
on:
  push:
    paths:
      - .github/workflows/test.yml
      - action.yml
  workflow_dispatch:
    inputs:
      credential:
        description: "Credential for basic authentication (format: username:password)"
        required: false
      command:
        description: "Command to run"
        required: false
        default: ""
        type: string
      enableUrlArg:
        description: "Enable URL argument"
        required: false
        default: false
        type: boolean
      port:
        description: "Port for ttyd server"
        required: false
        type: number
        default: 7681
      enableZmodem:
        description: "Enable Zmodem support"
        required: false
        default: true
        type: boolean
      enableTrzsz:
        description: "Enable Trzsz support"
        type: boolean
        default: true
        required: false
      enableSixel:
        description: "Enable Sixel support"
        type: boolean
        default: true
        required: false

jobs:
  test:
    name: Test on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v7

    - name: Check inputs
      run: |
        echo "inputs: ${{ inputs }}"
        
    - uses: ./
      with:
        command: ${{ inputs.command }}
        enableUrlArg: ${{ inputs.enableUrlArg }}
        credential: ${{ inputs.credential|| secrets.TTYD_CREDENTIAL }}
        port: ${{ inputs.port }}
        enableZmodem: ${{ inputs.enableZmodem }}
        enableTrzsz:  ${{ inputs.enableTrzsz }}
        enableSixel: ${{ inputs.enableSixel }}

    - name: Keep alive
      shell: bash
      run: sleep 5m
