name: Test
on:
  push:
    paths:
      - .github/workflows/test.yml
      - action.yml
  workflow_dispatch:
    inputs:
      writable:
        description: "Make the terminal writable"
        required: false
        default: false
        type: boolean
      command:
        description: "Command to run"
        required: false
        default: "bash -l"
    #   ttyd-credential:
    #     description: "Credential for basic authentication (format: username:password)"
    #     required: false
    #   port:
    #     description: "Port for ttyd server, optional, default is 7681"
    #     required: false
    #   enableZmodem:
    #     description: "Enable Zmodem support, optional, deafult is true"
    #     required: false
    #   enableTrzsz:
    #     description: "Enable Trzsz support, optional, default is true"
    #     required: false
    #   enableSixel:
    #     description: "Enable Sixel support, optional, default is true"
    #     required: false

jobs:
  test:
    name: Test on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v7
    - uses: ./
      with:
        writable: ${{ inputs.writable }}
        command: ${{ inputs.command }}
        # credential: user:${{ inputs.ttyd-credential|| secrets.TTYD_CREDENTIAL }}
        # port: ${{ inputs.port }}
        # enableZmodem: ${{ inputs.enableZmodem }}
        # enableTrzsz:  ${{ inputs.enableTrzsz }}
        # enableSixel: ${{ inputs.enableSixel }}

    - name: Keep alive
      shell: bash
      run: sleep 5m
