name: Test
on:
  push:
    paths:
      - .github/workflows/test.yml
      - action.yml
  workflow_dispatch:
    inputs:
      credential:
        description: "Credential for basic authentication (format: username:password)"
        required: false
      port:
        description: "Port for ttyd server"
        required: false
        type: number
        default: 7681
      enableZmodem:
        description: "Enable Zmodem support"
        required: false
        default: true
        type: boolean
      enableTrzsz:
        description: "Enable Trzsz support"
        type: boolean
        default: true
        required: false
      enableSixel:
        description: "Enable Sixel support"
        type: boolean
        default: true
        required: false

jobs:
  test:
    name: Test on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v7
    - uses: ./
      with:
        credential: user:${{ inputs.credential|| secrets.TTYD_CREDENTIAL }}
        port: ${{ inputs.port }}
        enableZmodem: ${{ inputs.enableZmodem }}
        enableTrzsz:  ${{ inputs.enableTrzsz }}
        enableSixel: ${{ inputs.enableSixel }}

    - name: Keep alive
      shell: bash
      run: sleep 5m
